# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zipconverter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 595)
        MainWindow.setMinimumSize(QtCore.QSize(100, 100))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/favicon-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_view = QtWidgets.QListView(self.centralwidget)
        self.list_view.setGeometry(QtCore.QRect(20, 120, 501, 311))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.list_view.setFont(font)
        self.list_view.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(64, 64, 64);\n"
"border-color: rgb(115, 115, 115);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"padding: 5px;")
        self.list_view.setObjectName("list_view")
        self.button_converter = QtWidgets.QPushButton(self.centralwidget)
        self.button_converter.setGeometry(QtCore.QRect(20, 500, 501, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_converter.setFont(font)
        self.button_converter.setStyleSheet("background-color: rgb(166, 166, 166);\n"
"color: rgb(64, 64, 64);\n"
"border-color: rgb(115, 115, 115);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.button_converter.setObjectName("button_converter")
        self.button_select = QtWidgets.QPushButton(self.centralwidget)
        self.button_select.setGeometry(QtCore.QRect(20, 80, 501, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_select.setFont(font)
        self.button_select.setStyleSheet("background-color: rgb(166, 166, 166);\n"
"color: rgb(64, 64, 64);\n"
"border-color: rgb(115, 115, 115);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.button_select.setObjectName("button_select")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background-color: rgb(115, 115, 115);\n"
"color: rgb(242, 242, 242);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.check_box.setGeometry(QtCore.QRect(30, 450, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_box.setFont(font)
        self.check_box.setStyleSheet("color: rgb(64, 64, 64);\n"
"")
        self.check_box.setObjectName("check_box")
        self.edit_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_pass.setGeometry(QtCore.QRect(110, 450, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.edit_pass.setFont(font)
        self.edit_pass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(64, 64, 64);\n"
"border-color: rgb(115, 115, 115);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"padding-left: 5px;")
        self.edit_pass.setObjectName("edit_pass")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(20, 550, 501, 23))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_converter.setText(_translate("MainWindow", "Compactar"))
        self.button_select.setText(_translate("MainWindow", "Selecionar Arquivos"))
        self.label_title.setText(_translate("MainWindow", "Zip Compactor"))
        self.check_box.setText(_translate("MainWindow", "Senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
