# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # MainWindow declaration and config
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/favicon-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(60, 60, 60);\n"
                                 "color: rgb(242, 242, 242);")

        # Central widget declaration
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        # Label title declaration and config
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 200, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background-color: rgb(64, 66, 67);\n"
                                       "color: rgb(242, 242, 242);\n"
                                       "border-radius: 10px;")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")

        # List widget declaration and config
        self.list_view = QtWidgets.QListWidget(self.centralwidget)
        self.list_view.setGeometry(QtCore.QRect(220, 10, 571, 551))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.list_view.setFont(font)
        self.list_view.setStyleSheet("background-color: rgb(78, 78, 78);\n"
                                     "color: rgb(242, 242, 242);\n"
                                     "border-color: rgb(160, 160, 160);\n"
                                     "border-radius: 10px;\n"
                                     "border-width: 1px;\n"
                                     "border-style: solid;\n"
                                     "padding: 5px;")
        self.list_view.setObjectName("list_view")

        # Button select declaration and config
        self.button_select = QtWidgets.QPushButton(self.centralwidget)
        self.button_select.setGeometry(QtCore.QRect(10, 110, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_select.sizePolicy().hasHeightForWidth())
        self.button_select.setSizePolicy(sizePolicy)
        self.button_select.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_select.setFont(font)
        self.button_select.setStyleSheet("background-color: rgb(64, 66, 67);\n"
                                         "color: rgb(242, 242, 242);\n"
                                         "border-color: rgb(160, 160, 160);\n"
                                         "border-radius: 10px;\n"
                                         "border-width: 1px;\n"
                                         "border-style: solid;")
        self.button_select.setObjectName("button_select")

        # Button converter declaration and config
        self.button_converter = QtWidgets.QPushButton(self.centralwidget)
        self.button_converter.setGeometry(QtCore.QRect(10, 160, 201, 25))
        self.button_converter.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_converter.setFont(font)
        self.button_converter.setStyleSheet("background-color: rgb(64, 66, 67);\n"
                                            "color: rgb(242, 242, 242);\n"
                                            "border-color: rgb(160, 160, 160);\n"
                                            "border-radius: 10px;\n"
                                            "border-width: 1px;\n"
                                            "border-style: solid;")
        self.button_converter.setObjectName("button_converter")

        # Button extract declaration and config
        self.button_extract = QtWidgets.QPushButton(self.centralwidget)
        self.button_extract.setGeometry(QtCore.QRect(10, 210, 201, 25))
        self.button_extract.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_extract.setFont(font)
        self.button_extract.setStyleSheet("background-color: rgb(64, 66, 67);\n"
                                          "color: rgb(242, 242, 242);\n"
                                          "border-color: rgb(160, 160, 160);\n"
                                          "border-radius: 10px;\n"
                                          "border-width: 1px;\n"
                                          "border-style: solid;")
        self.button_extract.setObjectName("button_extract")

        # Menu bar declaration and config
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("color: rgb(160, 160, 160);")
        self.menuBar.setObjectName("menuBar")

        # Menu about declaration and config
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setStyleSheet("color: rgb(242, 242, 242);")
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zip Compactor"))
        self.label_title.setText(_translate("MainWindow", "Zip Compactor"))
        self.button_select.setText(_translate("MainWindow", "Select Files"))
        self.button_converter.setText(_translate("MainWindow", "Compact"))
        self.button_extract.setText(_translate("MainWindow", "Extract Files"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
