# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zip_screen_confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 150)
        Dialog.setMinimumSize(QtCore.QSize(250, 150))
        Dialog.setMaximumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.confirm_pass = QtWidgets.QLineEdit(Dialog)
        self.confirm_pass.setGeometry(QtCore.QRect(9, 36, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.confirm_pass.setFont(font)
        self.confirm_pass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(64, 64, 64);\n"
"border-color: rgb(115, 115, 115);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"padding-left: 5px;")
        self.confirm_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_pass.setObjectName("confirm_pass")
        self.button_confirm = QtWidgets.QPushButton(Dialog)
        self.button_confirm.setGeometry(QtCore.QRect(70, 90, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_confirm.sizePolicy().hasHeightForWidth())
        self.button_confirm.setSizePolicy(sizePolicy)
        self.button_confirm.setMinimumSize(QtCore.QSize(100, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_confirm.setFont(font)
        self.button_confirm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_confirm.setStyleSheet("background-color: rgb(166, 166, 166);\n"
"color: rgb(64, 64, 64);\n"
"border-color: rgb(115, 115, 115);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.button_confirm.setObjectName("button_confirm")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Confirm Password"))
        self.button_confirm.setText(_translate("Dialog", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
